### ISSUE TITLE
Please update location of MyTAP repository

### ISSUE THREAD

**Issue by hepabolu** [TestAnything/testanything.github.io#114]
As of June 4, 2017 I am the new owner of the MyTAP repository. Please update the link from theory.github.io/mytap to hepabolu.github.io/mytap

**Comment by mblayman** [comment]
Hi, @hepabolu. The TAP website is maintained by the community. You are welcome to update the link yourself in the form of a pull request.

**Comment by hepabolu** [comment]
Pull request added (#115)

**Comment by mblayman** [comment]
Fixed.
