### ISSUE TITLE
new TAP producer/consumer on the horrizon...

### ISSUE THREAD

**Issue by ebo** [TestAnything/testanything.github.io#122]
Working with my intern last summer, we wrote a simple CI/CD dashboard that conforms to NASA's agency restrictions and guidelines to assist project level unit and regression testing.  We are *almost* though the open-source release process.  When we get approval, I would like to see if someone can do a review before it is fully released to the public.  Any takers?  As a note, this will, as far as I know, end up being an official NASA open source product.

**Comment by mblayman** [comment]
Hi @ebo, I appreciate NASA releasing something as open source, however, these issues are for the maintenance of the testanything.org website or for issues related to the protocol specs.

There is not a clear action path for closing this issue. Also, this repo is *extremely* low traffic. I've been the sole maintainer of this site for well over a year. So, you got my attention, but that's probably about it. And I don't have the time to review a tool.

If you're looking for visibility for some to review, I'd suggest looking for a different channel.

**Comment by plroebuck** [comment]
@ebo, did your producer make it through the process? Link?

**Comment by ebo** [comment]
On Sep 19 2018 12:50 PM, P. Roebuck wrote:
> @ebo, did your producer make it through the process? Link?

Yes.  It took something like a year -- problems with the new online 
forms having a bug.

The intern and I still need to clean up the code and have a few details 
reviewed for agency correctness, and then publicly release.

At the moment my house is being renovated and I have to deal with that. 
Can you check in with me a couple of months to help keep this on the 
stack?
