### ISSUE TITLE
more about C TAP producers ?

### ISSUE THREAD

**Issue by eiro** [TestAnything/testanything.github.io#134]
there are 3 C TAP producers.

* https://www.shlomifish.org/open-source/projects/libtap/ (i call it A)
* http://github.com/zorgnax/libtap (i call it B)
* http://www.eyrie.org/~eagle/software/c-tap-harness/ (i call it C)

the page of A says B seems better and there is no information about how it compares to C. we could contact the authors and ask them to clarify?

thanks for all the work

**Comment by mblayman** [comment]
We try to offer an unbiased opinion about TAP producers/consumers on testanything.org. The focus of testanything.org is to show all the options that are available to each of the different language ecosystems.

Given that, you're welcome to contact those individuals to see if they will document their rationale better for their respective project, but that information of why A is better than B (or vice-versa) does not need to go on testanything.org.

**Comment by eiro** [comment]
hello,

> Given that, you're welcome to contact those individuals to see if they
> will document their rationale better for their respective project, but
> that information of why A is better than B (or vice-versa) does not
> need to go on testanything.org.

ok. i'll try to investigate :)

regards
marc
