### ISSUE TITLE
You could mention Qt's QtTestLib as a TAP producer

### ISSUE THREAD

**Issue by ediosyncratic** [TestAnything/testanything.github.io#162]
The Qt Test testing framework [0] supports output in TAP format, when the test binary is passed the ```-tap``` command-line option [1]. (I would welcome any bug reports against the output it produces, if it turns out to be out of date or otherwise imperfect.) A mention on your list of producers would be welcome ;^>

[0] https://doc.qt.io/qt-6/qttest-index.html
[1] https://doc.qt.io/qt-6/qtest-overview.html#logging-options

**Comment by mblayman** [comment]
The content on the TAP website is entirely driven by the community. If you'd like to submit a PR to the TAP producers page, I'd be happy to accept it as long as it follows the format of that page.

**Comment by ediosyncratic** [comment]
Implemented as pull request:
https://github.com/TestAnything/testanything.github.io/pull/163
but I have no idea who to add as reviewers.

**Comment by ediosyncratic** [comment]
Nor can I find any UI by which to *add* a reviewer, although there are red alerts telling me I need one.

**Comment by ediosyncratic** [comment]
According to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review
there should be some suggested reviewers listed under the Reviewers part of the right-hand panel; but there are none, so I am not offered any button to click on to request review by any of the suggested reviewers; and github provides no other means for means for me to add a reviewer.
So I have created a pull request as suggested, but have no idea how to proceed beyond that :-(

**Comment by mblayman** [comment]
Merged!
