### ISSUE TITLE
Node test runner is a tap producer

### ISSUE THREAD

**Issue by jwrightecs** [TestAnything/testanything.github.io#167]
https://nodejs.org/dist/latest-v18.x/docs/api/test.html

**Comment by mblayman** [comment]
testanything.org is community managed for all contributions to the producers and consumers page. Feel free to submit a PR for the producers page. As long as the change follows a similar format as other producers on that page, I'll accept it. 😁

**Comment by mblayman** [comment]
Fixed with #173
