### ISSUE TITLE
bayeux and yamlish

### ISSUE THREAD

**Issue by mcepl** [TestAnything/testanything.github.io#24]
Could I ask for adding two Python projects:

* [bayeux](https://pypi.python.org/pypi/bayeux/) is a module generating TAP stream (includes also `unittest_tap` which works as a shell over the standard Python `unittest` package)
* [yamlish](https://pypi.python.org/pypi/yamlish) is a shell over [PyYaml](https://pypi.python.org/pypi/PyYAML) for parsing and generating Yamlish stream.

**Comment by kinow** [comment]
Hi @mcepl!

Sure, we'll take a look at it later. Or you can submit a pull request with your contributions :-) That would probably be faster.

Thanks!
Bruno

**Comment by mcepl** [comment]
Well, I hoped I could be lazy and that you would actually understand better how to update the repo. Here is the suggested pull request.

**Comment by kinow** [comment]
You could, it just would take a bit longer :-)
