### ISSUE TITLE
Un-indent TAP examples

### ISSUE THREAD

**Issue by isaacs** [TestAnything/testanything.github.io#31]
In the examples in the specification, they're all indented several spaces.  In one example, under "Unknown amount and failures", the `TAP Version 13` is indented one space *more* than the lines that follow, which I think is invalid.

```
    TAP version 13
   ok 1 - retrieving servers from the database
   # need to ping 6 servers
```

In order to make it easier to copy and paste these examples into test programs, it would be better if they were not indented with spaces.  If the spacing is for visual esthetics, then CSS would be a better tool.

**Comment by jonathanKingston** [comment]
Thank you for reporting this :+1:
