### ISSUE TITLE
Document Slack and other forms of communication

### ISSUE THREAD

**Issue by mblayman** [TestAnything/testanything.github.io#55]
I saw reference to a Slack group for the first time in an issue comment. This is not documented on the site and it's not clear how to get on there. When I clicked the link, it looked like I have to be added by an administrator.

I think the site would benefit from a page that describes how to get involved with TAP, the spec, the site, whatever.

**Comment by jonathanKingston** [comment]
I rarely go on this, I have pretty big reservations on it's success. I have seen healthy projects like cssnext and even ESLint have pretty dead chat channels so I'm unsure on it's worth personally.

Happy for this to go in if there is enough interest.

**Comment by mblayman** [comment]
Yeah, I don't really care that much if it's Slack or something else. I'm just hoping that any communication channels are out in the open. For instance, there's a email list at IETF, https://www.ietf.org/mailman/listinfo/tap. Should that be documented on the site?

**Comment by jonathanKingston** [comment]
I don't see point in documenting channels that won't be used - a mailing list that doesn't respond seems pointless. I mailed out to that list and various others which didn't seem to make any difference.
Again happy to defer the decision to others, I think there is mention to Reddit too which isn't used either.

**Comment by mblayman** [comment]
I wonder if it's a chicken and egg problem. Maybe there aren't responses on the mailing list because interested people don't know that it exists. Anyway, if all the discussion happens on GitHub issues, then maybe that is what is worth documenting so folks visiting testanything.org know how to get involved.

I know there are links to the GitHub repo on the bottom of the page, however, there isn't any guidance about what people could/should do.

**Comment by jonathanKingston** [comment]
> I wonder if it's a chicken and egg problem.

It is certainly however the subreddit was suggested by @kinow and only used by him last time I checked. I'm in two minds about this as I think TAP is super old as software formats go and so I think the interest is always limited. I'm certainly more pro on getting interest through to here.

> I know there are links to the GitHub repo on the bottom of the page, however, there isn't any guidance about what people could/should do.

Yup I can write this if you prefer.

**Comment by mblayman** [comment]
Go for it. :smile:

**Comment by mblayman** [comment]
Cleaning up a bit. There is lack of interest in doing this so I'm closing it.
