### ISSUE TITLE
Discuss removal of Non Proliferation comments

### ISSUE THREAD

**Issue by jonathanKingston** [TestAnything/testanything.github.io#59]
>Non Proliferation
TAP producer authors should be aware of (and hopefully sign) the TAP Namespace Nonproliferation Treaty

These comments in the pages have existed for a long time.

I would like to remove them because:
- I don't think it helps making TAP a usable format across other languages
- I don't think it actually helps solve any issue
- I think it makes the TAP community look closed and require a license somewhat

Discuss!

**Comment by mblayman** [comment]
I'm in favor of removing it. And if others don't want to remove it, then maybe we could at least refocus it on Perl where it originated.

It was a reasonable thing to have for Perl because namespacing is hard. I agree with you that it doesn't help to make TAP usable across languages.
